name: "hello world workflow"


on:
  push:
     branch:
     - master
     - production


jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      - uses: action/checkout@v2

      - name: hello world
        run: echo "hello world"