name: Hello World Workflow

on: [push]  # Runs every time you push to GitHub

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Say Hello World
        run: echo "Hello, Aman! GitHub Actions are working 🚀"
