name: Hello World Workflow

on:
  push:
    branches:
      - master  # or 'main' if your default branch is 'main'

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Hello
        run: echo "🎉 Hello from GitHub Actions!"
