name: Hello World Workflow

on:
  push:
    branches:
      - master  # triggers when you push to master branch

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "👋 Hello from Aman!"


