name: Hello World Workflow

on:
  push:
    branches:
      - master

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Hello
        run: echo "Hello Aman!"
