name: Hello World Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  hello:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu version

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the repository code

      - name: Say Hello
        run: echo "🎉 Hello from GitHub Actions!"
